// <auto-generated />
using System;
using Kronos.WebAPI.Hermes.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kronos.WebAPI.Migrations.Hermes
{
    [DbContext(typeof(HermesDbContext))]
    [Migration("20241115103119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hermes")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kronos.WebAPI.Hermes.SDK.TokenCryptoDataModel", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("EncryptionKey")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SigningKey")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("bytea");

                    b.HasKey("EntityId");

                    b.ToTable("TokenCryptoData", "hermes");
                });
#pragma warning restore 612, 618
        }
    }
}
