services:
  api:
    build:
      dockerfile: ./Dockerfile.Kronos.WebApi
      context: ../src/Kronos.WebAPI
    environment:
      - ASPNETCORE_URLS=https://+:7115;http://+:5108
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    ports:
      - "7115:7115"
      - "5108:5108"
    networks:
      - kronos
    volumes:
      - ../.aspnet/https:/https/  # Mount the certificate volume
networks:
  kronos:
      
      