services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    # volumes:
      # - ./data/:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - kronos
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  kronos: