services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_USER=root
      - POSTGRES_DB=pantheon
    networks:
      - kronos

networks:
  kronos: