name: Docker image (Kronos)

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
  workflow_dispatch:


jobs:
  push_to_registry:
    name: Push Docker image to Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: ghcr.io/patheon-temple/kronos:latest

  instruct_docker:
    name: Pull image and restart
    needs: [ push_to_registry ]
    uses: ./.github/workflows/docker-stack-restart.yml
    with:
      do-upload-compose: false
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      GH_PAT: ${{ secrets.GH_PAT }}
